
//create new user
POST  http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
 
 "UserName": "naha",
  "Password" : "dhggf2333",
  "Email" : "maha@gmail.com"
}

###
//create new Address
POST  http://localhost:5000/api/v1/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5ZDQ5OTZlZC1iZTJjLTQwNmItODI4Yy0yNDMyZWI3YTc5YjUiLCJ1bmlxdWVfbmFtZSI6Im5vb3IiLCJyb2xlIjoiQ3VzdG9tZXIiLCJuYmYiOjE3Mjc5NjAwMDIsImV4cCI6MTcyNzk2MDMwMiwiaWF0IjoxNzI3OTYwMDAyLCJpc3MiOiJMb2NhbGhvc3RJc3N1ZXIiLCJhdWQiOiJMb2NhbGhvc3RBdWRpZW5jZSJ9.7p4qbZ8_X9nL24M0r0uCQzpzvCtNFC-2u_4piXiNCHw
Content-Type: application/json

{
  "City": "Tabuk",
  "Neighberhood" : "al-manamah",
  "Street" : " bin majed",
  "UserId" : "4201ba59-7b60-43e7-9520-408de89d7942"
}

###
//Customer Login
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "Password" : "dhggf2333",
  "Email" : "maha@gmail.com"

}

###
// Admin Login - shahad
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "Password" : "dhggf2333",
  "Email" : "shahd@gmail.com"

}
###

// create Admin - The id is for Shahad user 
PUT  http://localhost:5000/api/v1/users/create-admin/740aadb5-5446-4511-858a-cdc6cabf3165
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3NDBhYWRiNS01NDQ2LTQ1MTEtODU4YS1jZGM2Y2FiZjMxNjUiLCJ1bmlxdWVfbmFtZSI6InNoYWhkIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzI4MjkzMTUwLCJleHAiOjE3MjgzMTExNTAsImlhdCI6MTcyODI5MzE1MCwiaXNzIjoiTG9jYWxob3N0SXNzdWVyIiwiYXVkIjoiTG9jYWxob3N0QXVkaWVuY2UifQ.zU1eTFUOyMYelIQwbq__KwYlVE2zmb0PcPo63OB3Guc
###

//get all users -admin auth
GET http://localhost:5000/api/v1/users
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3NDBhYWRiNS01NDQ2LTQ1MTEtODU4YS1jZGM2Y2FiZjMxNjUiLCJ1bmlxdWVfbmFtZSI6InNoYWhkIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzI4MjkzNTY3LCJleHAiOjE3MjgzMTE1NjcsImlhdCI6MTcyODI5MzU2NywiaXNzIjoiTG9jYWxob3N0SXNzdWVyIiwiYXVkIjoiTG9jYWxob3N0QXVkaWVuY2UifQ.6-bVu-tgdoyrARTNEowgv6H7vQK1bmSmCFmr70QCjMI
###

//get user by id -customer auth

GET http://localhost:5000/api/v1/users/41b8e212-0318-42b8-ad5b-3aae4bdd29d0
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI0MWI4ZTIxMi0wMzE4LTQyYjgtYWQ1Yi0zYWFlNGJkZDI5ZDAiLCJ1bmlxdWVfbmFtZSI6InJlaGFiIiwicm9sZSI6IkN1c3RvbWVyIiwibmJmIjoxNzI4MjkzNjYxLCJleHAiOjE3MjgzMTE2NjEsImlhdCI6MTcyODI5MzY2MSwiaXNzIjoiTG9jYWxob3N0SXNzdWVyIiwiYXVkIjoiTG9jYWxob3N0QXVkaWVuY2UifQ.-XgKdt3nLdzzdYjx6UfQ7KoTbA7YhUNo5-V1FGKTHu0
###

// user searching - admin auth
GET http://localhost:5000/api/v1/users?sortBy=UserName&sortOrder=asc&pageNumber=1&pageSize=10&searchTerm=shahd
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3NDBhYWRiNS01NDQ2LTQ1MTEtODU4YS1jZGM2Y2FiZjMxNjUiLCJ1bmlxdWVfbmFtZSI6InNoYWhkIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzI4MjkzNTY3LCJleHAiOjE3MjgzMTE1NjcsImlhdCI6MTcyODI5MzU2NywiaXNzIjoiTG9jYWxob3N0SXNzdWVyIiwiYXVkIjoiTG9jYWxob3N0QXVkaWVuY2UifQ.6-bVu-tgdoyrARTNEowgv6H7vQK1bmSmCFmr70QCjMI

###

//update user - customer auth
PUT  http://localhost:5000/api/v1/users/20f32d56-dd43-40d1-b4d9-a741a3ed3db7
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI0MWI4ZTIxMi0wMzE4LTQyYjgtYWQ1Yi0zYWFlNGJkZDI5ZDAiLCJ1bmlxdWVfbmFtZSI6InJlaGFiIiwicm9sZSI6IkN1c3RvbWVyIiwibmJmIjoxNzI4MjkzNjYxLCJleHAiOjE3MjgzMTE2NjEsImlhdCI6MTcyODI5MzY2MSwiaXNzIjoiTG9jYWxob3N0SXNzdWVyIiwiYXVkIjoiTG9jYWxob3N0QXVkaWVuY2UifQ.-XgKdt3nLdzzdYjx6UfQ7KoTbA7YhUNo5-V1FGKTHu0
Content-Type: application/json

{
  "UserName" : "shahad alzoman"
  
}
###
// delete user - admin auth
DELETE http://localhost:5000/api/v1/users/d477a701-21b2-4056-8de0-00ef832f4ca1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3NDBhYWRiNS01NDQ2LTQ1MTEtODU4YS1jZGM2Y2FiZjMxNjUiLCJ1bmlxdWVfbmFtZSI6InNoYWhkIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzI4MjkzNTY3LCJleHAiOjE3MjgzMTE1NjcsImlhdCI6MTcyODI5MzU2NywiaXNzIjoiTG9jYWxob3N0SXNzdWVyIiwiYXVkIjoiTG9jYWxob3N0QXVkaWVuY2UifQ.6-bVu-tgdoyrARTNEowgv6H7vQK1bmSmCFmr70QCjMI

###
POST http://localhost:5125/api/v1/orders
Content-Type: application/json

{
  "TotalAmount" : 54444,
  "UserId" : "799d50c3-8582-4f37-8124-100ef75d9b7c"
}

###
//category

// create category - admin auth

POST  http://localhost:5000/api/categories
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3NDBhYWRiNS01NDQ2LTQ1MTEtODU4YS1jZGM2Y2FiZjMxNjUiLCJ1bmlxdWVfbmFtZSI6InNoYWhkIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzI4MjkzNTY3LCJleHAiOjE3MjgzMTE1NjcsImlhdCI6MTcyODI5MzU2NywiaXNzIjoiTG9jYWxob3N0SXNzdWVyIiwiYXVkIjoiTG9jYWxob3N0QXVkaWVuY2UifQ.6-bVu-tgdoyrARTNEowgv6H7vQK1bmSmCFmr70QCjMI
Content-Type: application/json 

{
  "categoryName" : "category57"
  
}

###
// get all categories 
GET  http://localhost:5000/api/categories
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3NDBhYWRiNS01NDQ2LTQ1MTEtODU4YS1jZGM2Y2FiZjMxNjUiLCJ1bmlxdWVfbmFtZSI6InNoYWhkIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzI4MjkzNTY3LCJleHAiOjE3MjgzMTE1NjcsImlhdCI6MTcyODI5MzU2NywiaXNzIjoiTG9jYWxob3N0SXNzdWVyIiwiYXVkIjoiTG9jYWxob3N0QXVkaWVuY2UifQ.6-bVu-tgdoyrARTNEowgv6H7vQK1bmSmCFmr70QCjMI

###
// delete categories - admin auth
DELETE   http://localhost:5000/api/categories/f7c7451a-3c5a-446a-b2fe-b725b63eca8e
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3NDBhYWRiNS01NDQ2LTQ1MTEtODU4YS1jZGM2Y2FiZjMxNjUiLCJ1bmlxdWVfbmFtZSI6InNoYWhkIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzI4MjkzNTY3LCJleHAiOjE3MjgzMTE1NjcsImlhdCI6MTcyODI5MzU2NywiaXNzIjoiTG9jYWxob3N0SXNzdWVyIiwiYXVkIjoiTG9jYWxob3N0QXVkaWVuY2UifQ.6-bVu-tgdoyrARTNEowgv6H7vQK1bmSmCFmr70QCjMI

###

//products 

// creat productb - admin auth
POST   http://localhost:5000/api/products
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3NDBhYWRiNS01NDQ2LTQ1MTEtODU4YS1jZGM2Y2FiZjMxNjUiLCJ1bmlxdWVfbmFtZSI6InNoYWhkIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzI4MjkzNTY3LCJleHAiOjE3MjgzMTE1NjcsImlhdCI6MTcyODI5MzU2NywiaXNzIjoiTG9jYWxob3N0SXNzdWVyIiwiYXVkIjoiTG9jYWxob3N0QXVkaWVuY2UifQ.6-bVu-tgdoyrARTNEowgv6H7vQK1bmSmCFmr70QCjMI
Content-Type: application/json 

{
  "ProductName" : "phones",
  "Description": "good ",
  "Price" : 400,
   "Quantity": 33,
   "categoryId": "0c5abc35-9cfe-429a-8afb-0b1d67fc3b9c",
    "Image": "wwww"

}


### 
//create new order => customer
POST   http://localhost:5000/api/orders
Content-Type: application/json 

{
  "totalAmount" : 200
} 
###
//get all orders => customer
GET  http://localhost:5000/api/orders

###
//get order by id => admin auth
GET  http://localhost:5000/api/orders/{}

###
//delete order by id => customer
DELETE   http://localhost:5000/api/orders/{}

###
PUT http://localhost:5000/api/orders/{}
{
  "shipmentDate": 08/10/24
}

### 
//create new shipment => admin
POST   http://localhost:5000/api/shipments
Content-Type: application/json 

{
  
} 
###
//get all shipment => admin
GET  http://localhost:5000/api/shipments

###
//get shipment by id => admin auth
GET  http://localhost:5000/api/shipments/{}

###
//delete shipment by id => admin
DELETE   http://localhost:5000/api/shipment/{}

###
